name: cotr_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  auto_route: ^9.2.2
  collection: ^1.17.1
  device_info_plus: ^11.1.1
  flex_color_scheme: ^8.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0  
  flutter_web_plugins:
    sdk: flutter 
  flutter_svg: ^2.0.14  
  get_it: ^8.0.2 
  google_fonts: ^6.2.1 
  http: ^1.2.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.1
  shared_preferences: ^2.3.3
  universal_html: ^2.2.4
  universal_io: 2.2.2 
  url_launcher: ^6.3.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
